extern crate clap;

use clap::{App, Arg};

fn main() {
    let cmd = App::new("Evil")
        .version("0.0.1")
        .author("Snowfall99")
        .about("IS415 Group 8: Evil test")
        .subcommand(App::new("WRITE")
            .about("test WRITE privilege")
            .version("0.0.1")
            .arg(Arg::new("target")
                .short('t')
                .about("target file for write")))
        .subcommand(App::new("READ")
            .about("test READ privilege")
            .version("0.0.1")
            .arg(Arg::new("target")
                .short('t')
                .about("target file for read")))
        .subcommand(App::new("OPEN")
            .about("test OPEN privilege")
            .version("0.0.1")
            .arg(Arg::new("target")
                .short('t')
                .about("target file for open")))
        .subcommand(App::new("CHMOD")
            .about("test CHMOD privilege")
            .version("0.0.1")
            .arg(Arg::new("target")
                .short('t')
                .about("target file for chmod")))
        .subcommand(App::new("CREAT")
            .about("test CREAT privilege")
            .version("0.0.1")
            .arg(Arg::new("target")
                .short('t')
                .about("target file for creat")))
        .subcommand(App::new("MKDIR")
            .about("test MKDIR privilege")
            .version("0.0.1")
            .arg(Arg::new("target")
                .short('t')
                .about("target file for mkdir")))
        .subcommand(App::new("RMDIR")
            .about("test RMDIR privilege")
            .version("0.0.1")
            .arg(Arg::new("target")
                .short('t')
                .about("target file for rmdir")))
        .get_matches();
}
